# Generated by Django 4.2.15 on 2025-08-29 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("device_monitoring", "0009_update_device_status_for_disabled_critical_checks"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpokeStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SpokeStatus_reports",
                        to=settings.DEVICE_MONITORING_DEVICEDATA_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="device_moni_device__fa89ad_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IpsecTunnels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="IpsecTunnels_reports",
                        to=settings.DEVICE_MONITORING_DEVICEDATA_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="device_moni_device__ed6f0c_idx",
                    )
                ],
            },
        ),
    ]
