# Generated by Django 5.2.6 on 2025-09-18 07:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device_monitoring", "0010_spokestatus_ipsectunnels"),
    ]

    operations = [
        migrations.CreateModel(
            name="WanStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("raw", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wanstatus_reports",
                        to=settings.DEVICE_MONITORING_DEVICEDATA_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WanInterfaceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interface", models.CharField(max_length=64)),
                ("nic_device", models.CharField(blank=True, max_length=64, null=True)),
                ("up", models.BooleanField(db_index=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interface_statuses",
                        to=settings.DEVICE_MONITORING_DEVICEDATA_MODEL,
                    ),
                ),
                (
                    "wan_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interfaces",
                        to="device_monitoring.wanstatus",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp", "interface"],
            },
        ),
        migrations.CreateModel(
            name="ClientSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_summaries",
                        to=settings.DEVICE_MONITORING_DEVICEDATA_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="device_moni_device__fc09fa_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConfigPush",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_push_reports",
                        to=settings.DEVICE_MONITORING_DEVICEDATA_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="device_moni_device__a26387_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DPIRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dpi_records",
                        to=settings.DEVICE_MONITORING_DEVICEDATA_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="device_moni_device__737527_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InerfaceEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interface_events_reports",
                        to=settings.DEVICE_MONITORING_DEVICEDATA_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="device_moni_device__3c5ebc_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InterfaceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interface_list_reports",
                        to=settings.DEVICE_MONITORING_DEVICEDATA_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="device_moni_device__3919ca_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InterfaceTraffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interface_traffic_reports",
                        to=settings.DEVICE_MONITORING_DEVICEDATA_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="device_moni_device__ddbd39_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LatquaList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="latqua_reports",
                        to=settings.DEVICE_MONITORING_DEVICEDATA_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="device_moni_device__2a305d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RealTraffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="real_traffic_records",
                        to=settings.DEVICE_MONITORING_DEVICEDATA_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="device_moni_device__c7ed92_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TSIPReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tsip_reports",
                        to=settings.DEVICE_MONITORING_DEVICEDATA_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="device_moni_device__4cf1ad_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="wanstatus",
            index=models.Index(
                fields=["device", "timestamp"], name="device_moni_device__602b63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waninterfacestatus",
            index=models.Index(
                fields=["device", "interface"], name="device_moni_device__9155e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waninterfacestatus",
            index=models.Index(
                fields=["wan_status", "up"], name="device_moni_wan_sta_c7b094_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="waninterfacestatus",
            unique_together={("device", "interface")},
        ),
    ]
