# Generated by Django 4.2.16 on 2025-10-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "device_monitoring",
            "0011_wanstatus_waninterfacestatus_clientsummary_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wanstatus",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
