# Generated by Django 4.2.16 on 2025-10-01 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("device_monitoring", "0012_alter_wanstatus_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wanstatus",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
