# Generated by Django 4.2.16 on 2025-10-13 09:42

from django.db import migrations
import openwisp_monitoring.device.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("sdwan_tunnel", "0001_initial"),
        ("device_monitoring", "0013_alter_wanstatus_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="TunnelData",
            fields=[],
            options={
                "proxy": True,
                "swappable": "DEVICE_MONITORING_TUNNELDATA_MODEL",
                "indexes": [],
                "constraints": [],
            },
            bases=(
                openwisp_monitoring.device.base.models.AbstractTunnelData,
                "sdwan_tunnel.tunnel",
            ),
        ),
    ]
